name: Print File Contents

on:
  push:
    branches:
      - main

jobs:
  print-file-contents:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3
    - name: Setup Npm
      uses: actions/setup-node@v3
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        node-version: 12
        registry-url: https://npm.pkg.github.com/
        always-auth: true
    - name: Check a single existing package
      if: 'false'
      env:
        NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
      run: |
        echo "Checking a single package"
        package_name="com.stillfront.sound"
        package_version="2.0.3"
        echo " - Checking if $package_name@$package_version exists"
        npm show --registry="https://npm.pkg.github.com/@Stillfront" "$package_name@$package_version" version
        if [ $? -eq 0 ]; then
          echo "Package $package_name@$package_version exists on the remote registry."
        else
          echo "Package $package_name@$package_version does not exist on the remote registry."
        fi
    - name: Publish packages to NPM
      if: 'true'
      env:
        NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
      run: |
        for folder in "Packages"/*; do
          if [ -d "$folder" ]; then
            file_to_publish="$folder/package.json"
        
            if [ -e "$file_to_publish" ]; then
                package_name=$(grep -oPm 1 '"name": "\K[^"]+' $file_to_publish)
                package_version=$(grep -oPm 1 '"version": "\K[^"]+' $file_to_publish)
                package_registry=$(grep -oPm 1 '"registry": "\K[^"]+' $file_to_publish)
        
                # Deactivate exit on error
                set +e
                # Calling on version returns empty when the package does not exist or errors on any other failure
                result=$(npm show --registry="$package_registry" "$package_name@$package_version" version)
                exit_code=$?
                # Reactivate exit on error
                set -e
                if [[ "$result" == "$package_version" ]]; then
                  echo "Package $package_name@$package_version already exists."
                else
                  echo "Could not find package $package_name@$package_version. Publishing..." 
                  cd "$folder" || exit 1
                  # Deactivate exit on error
                  set +e
                  npm publish
                  # Reactivate exit on error
                  set -e
                  cd - || exit 2
                fi
            else
                echo "File package.json not found in $folder"
            fi
          fi
        done
        echo "Finished publishing all packages"